services:
  log-producer:
    build: ./producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-37582d23-ecylkk-00e1.j.aivencloud.com:24664
      - KAFKA_TOPIC=logs
      - KAFKA_CA_PATH=/app/certs/ca.pem
      - KAFKA_CERT_PATH=/app/certs/service.cert
      - KAFKA_KEY_PATH=/app/certs/service.key
    volumes:
      - ./certs:/app/certs:ro

  log-analyzer:
    build: ./consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-37582d23-ecylkk-00e1.j.aivencloud.com:24664
      - KAFKA_TOPIC=logs
      - KAFKA_CA_PATH=/app/certs/ca.pem
      - KAFKA_CERT_PATH=/app/certs/service.cert
      - KAFKA_KEY_PATH=/app/certs/service.key
    volumes:
      - ./certs:/app/certs:ro
